name: Backend CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs_on: ubuntu-latest

    steps:
      - name: Checkout
        users: actions/checkout@v4

      - name: Set up Java
        users: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      - name: Cache Maven repo
        users: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: m2-${{ runner.os }}-${{ hashFiles('**/pom.xml')}}
          restore-keys: m2-${{ runner.os }}-

      - name: Run tests
        run: mvn -B clean verify
